[package]
name = "ld51-dojo-panic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.80.0" #{ git = "https://github.com/bevyengine/bevy.git", branch = "main" }
bevy_rapier2d = "0.17.0"